2013-07-27 13:21:09,714 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 101, in get_response
    request.path_info)
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 298, in resolve
    for pattern in self.url_patterns:
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 328, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 323, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "C:\Python27\lib\site-packages\django\utils\importlib.py", line 35, in import_module
    __import__(name)
  File "C:\work\solo\www.freedomsponsors.org\djangoproject\frespo\urls.py", line 5, in <module>
    from core.forms import RegistrationForm
  File "C:\work\solo\www.freedomsponsors.org\djangoproject\core\forms.py", line 4, in <module>
    from registration.forms import RegistrationForm as _RegistrationForm
ImportError: No module named registration.forms
2013-07-27 13:21:12,206 [ERROR] django.request: Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 89, in get_response
    response = middleware_method(request)
  File "C:\Python27\lib\site-packages\django\middleware\common.py", line 67, in process_request
    if (not urlresolvers.is_valid_path(request.path_info, urlconf) and
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 531, in is_valid_path
    resolve(path, urlconf)
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 420, in resolve
    return get_resolver(urlconf).resolve(path)
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 298, in resolve
    for pattern in self.url_patterns:
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 328, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 323, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "C:\Python27\lib\site-packages\django\utils\importlib.py", line 35, in import_module
    __import__(name)
  File "C:\work\solo\www.freedomsponsors.org\djangoproject\frespo\urls.py", line 5, in <module>
    from core.forms import RegistrationForm
  File "C:\work\solo\www.freedomsponsors.org\djangoproject\core\forms.py", line 4, in <module>
    from registration.forms import RegistrationForm as _RegistrationForm
ImportError: No module named registration.forms
2013-07-27 13:21:16,096 [ERROR] django.request: Internal Server Error: /sandbox
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 89, in get_response
    response = middleware_method(request)
  File "C:\Python27\lib\site-packages\django\middleware\common.py", line 67, in process_request
    if (not urlresolvers.is_valid_path(request.path_info, urlconf) and
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 531, in is_valid_path
    resolve(path, urlconf)
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 420, in resolve
    return get_resolver(urlconf).resolve(path)
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 298, in resolve
    for pattern in self.url_patterns:
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 328, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 323, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "C:\Python27\lib\site-packages\django\utils\importlib.py", line 35, in import_module
    __import__(name)
  File "C:\work\solo\www.freedomsponsors.org\djangoproject\frespo\urls.py", line 5, in <module>
    from core.forms import RegistrationForm
  File "C:\work\solo\www.freedomsponsors.org\djangoproject\core\forms.py", line 4, in <module>
    from registration.forms import RegistrationForm as _RegistrationForm
ImportError: No module named registration.forms
2013-07-27 13:21:18,203 [ERROR] django.request: Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 89, in get_response
    response = middleware_method(request)
  File "C:\Python27\lib\site-packages\django\middleware\common.py", line 67, in process_request
    if (not urlresolvers.is_valid_path(request.path_info, urlconf) and
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 531, in is_valid_path
    resolve(path, urlconf)
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 420, in resolve
    return get_resolver(urlconf).resolve(path)
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 298, in resolve
    for pattern in self.url_patterns:
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 328, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 323, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "C:\Python27\lib\site-packages\django\utils\importlib.py", line 35, in import_module
    __import__(name)
  File "C:\work\solo\www.freedomsponsors.org\djangoproject\frespo\urls.py", line 5, in <module>
    from core.forms import RegistrationForm
  File "C:\work\solo\www.freedomsponsors.org\djangoproject\core\forms.py", line 4, in <module>
    from registration.forms import RegistrationForm as _RegistrationForm
ImportError: No module named registration.forms
2013-07-27 13:22:12,634 [ERROR] django.request: Internal Server Error: /sandbox
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 89, in get_response
    response = middleware_method(request)
  File "C:\Python27\lib\site-packages\django\middleware\common.py", line 67, in process_request
    if (not urlresolvers.is_valid_path(request.path_info, urlconf) and
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 531, in is_valid_path
    resolve(path, urlconf)
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 420, in resolve
    return get_resolver(urlconf).resolve(path)
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 298, in resolve
    for pattern in self.url_patterns:
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 328, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 323, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "C:\Python27\lib\site-packages\django\utils\importlib.py", line 35, in import_module
    __import__(name)
  File "C:\work\solo\www.freedomsponsors.org\djangoproject\frespo\urls.py", line 28
    )
    ^
SyntaxError: invalid syntax
2013-07-27 13:22:14,732 [ERROR] django.request: Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 89, in get_response
    response = middleware_method(request)
  File "C:\Python27\lib\site-packages\django\middleware\common.py", line 67, in process_request
    if (not urlresolvers.is_valid_path(request.path_info, urlconf) and
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 531, in is_valid_path
    resolve(path, urlconf)
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 420, in resolve
    return get_resolver(urlconf).resolve(path)
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 298, in resolve
    for pattern in self.url_patterns:
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 328, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 323, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "C:\Python27\lib\site-packages\django\utils\importlib.py", line 35, in import_module
    __import__(name)
  File "C:\work\solo\www.freedomsponsors.org\djangoproject\frespo\urls.py", line 28
    )
    ^
SyntaxError: invalid syntax
2013-07-27 13:22:28,453 [ERROR] django.request: Internal Server Error: /sandbox
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 89, in get_response
    response = middleware_method(request)
  File "C:\Python27\lib\site-packages\django\middleware\common.py", line 67, in process_request
    if (not urlresolvers.is_valid_path(request.path_info, urlconf) and
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 531, in is_valid_path
    resolve(path, urlconf)
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 420, in resolve
    return get_resolver(urlconf).resolve(path)
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 298, in resolve
    for pattern in self.url_patterns:
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 328, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 323, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "C:\Python27\lib\site-packages\django\utils\importlib.py", line 35, in import_module
    __import__(name)
  File "C:\work\solo\www.freedomsponsors.org\djangoproject\frespo\urls.py", line 5, in <module>
    from core.forms import RegistrationForm
  File "C:\work\solo\www.freedomsponsors.org\djangoproject\core\forms.py", line 4, in <module>
    from registration.forms import RegistrationForm as _RegistrationForm
ImportError: No module named registration.forms
2013-07-27 13:22:30,568 [ERROR] django.request: Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 89, in get_response
    response = middleware_method(request)
  File "C:\Python27\lib\site-packages\django\middleware\common.py", line 67, in process_request
    if (not urlresolvers.is_valid_path(request.path_info, urlconf) and
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 531, in is_valid_path
    resolve(path, urlconf)
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 420, in resolve
    return get_resolver(urlconf).resolve(path)
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 298, in resolve
    for pattern in self.url_patterns:
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 328, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 323, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "C:\Python27\lib\site-packages\django\utils\importlib.py", line 35, in import_module
    __import__(name)
  File "C:\work\solo\www.freedomsponsors.org\djangoproject\frespo\urls.py", line 5, in <module>
    from core.forms import RegistrationForm
  File "C:\work\solo\www.freedomsponsors.org\djangoproject\core\forms.py", line 4, in <module>
    from registration.forms import RegistrationForm as _RegistrationForm
ImportError: No module named registration.forms
2013-07-27 13:23:19,198 [ERROR] django.request: Internal Server Error: /sandbox/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\views\generic\simple.py", line 27, in direct_to_template
    t = loader.get_template(template)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 145, in get_template
    template, origin = find_template(template_name)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 138, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: sandbox/home.html
2013-07-27 13:23:21,311 [ERROR] django.request: Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 150, in get_response
    response = callback(request, **param_dict)
  File "C:\Python27\lib\site-packages\django\utils\decorators.py", line 91, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\django\views\defaults.py", line 20, in page_not_found
    t = loader.get_template(template_name) # You need to create a 404.html template.
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 145, in get_template
    template, origin = find_template(template_name)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 138, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: 404.html
